name: Android App Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

    # Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

# workflow permissions
permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

# workflow environment variables
env:
  FORCE_COLOR: 1
  TEST_ENV: ci
  # SHA: ${{ github.event.pull_request.head.sha }}
  # LOCAL_APP: ./apk/test.apk
  # SENDGRID_FROM: ${{secrets.SENDGRID_FROM}}
  # SENDGRID_HOST: ${{secrets.SENDGRID_HOST}}
  # SENDGRID_PORT: ${{secrets.SENDGRID_PORT}}
  # SENDGRID_USER: ${{secrets.SENDGRID_USER}}
  # SENDGRID_PASS: ${{secrets.SENDGRID_PASS}}
  SLACK_CHANNEL: ${{secrets.SLACK_CHANNEL}}
  SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}

jobs:
  test:
    name: app test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout testing repo
        uses: actions/checkout@v4

      - name: 🐢 Use Desired Version of NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: |
          npm ci || npm i

      - name: Run tests
        run: |
          npm run test

      # --- START OF ALLURE HISTORY LOGIC ---

      - name: 📥 Get Allure History
        if: always()
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-history
          sparse-checkout: |
            allure-history
          sparse-checkout-cone-mode: false

      - name: Remove allure-history redundent nested folder
        if: always()
        run: |
          mv allure-history/allure-history/* allure-history/ || true
          rmdir allure-history/allure-history || true

      - name: Generate Test report
        run: |
          npm run report:generate

      - name: Copy Allure History to Allure Report
        if: always()
        run: |
          if [ -d "allure-history" ]; then
            cp -r allure-history allure-report || true
          fi

      - name: 🚀 Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          keep_files: false

      # - name: Enable KVM
      #   run: |
      #     echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
      #     sudo udevadm control --reload-rules
      #     sudo udevadm trigger --name-match=kvm

      # - name: AVD cache
      #   uses: actions/cache@v4
      #   id: avd-cache
      #   with:
      #     path: |
      #       ~/.android/avd/*
      #       ~/.android/adb*
      #     key: avd-cache-34

      # - name: create AVD and generate snapshot for caching
      #   if: steps.avd-cache.outputs.cache-hit != 'true'
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 34
      #     target: google_atd
      #     arch: x86_64
      #     channel: stable
      #     force-avd-creation: true
      #     disable-animations: false
      #     emulator-options: -no-window -noaudio -no-boot-anim -gpu swiftshader_indirect
      #     script: echo "Generated AVD snapshot for caching."

      # - name: run tests
      #   id: emulator
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     # target: google_atd
      #     # arch: x86_64
      #     # channel: stable
      #     # force-avd-creation: false
      #     # disable-animations: true
      #     # disable-spellchecker: true
      #     emulator-options: -no-snapshot-save -no-window -noaudio -no-boot-anim -gpu swiftshader_indirect -camera-back none
      #     script: |
      #       echo "Emulator started and boot completed!" && set +e && true; EXIT_CODE=$?; set -e; echo "wdio_exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT; exit $EXIT_CODE
